// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNJgvJSfFNDtLYDpJQugiEUJaDk6YI6Mk',
    appId: '1:812205537802:web:fbf3d7944be739275a3df3',
    messagingSenderId: '812205537802',
    projectId: 'embti-6e22a',
    authDomain: 'embti-6e22a.firebaseapp.com',
    storageBucket: 'embti-6e22a.firebasestorage.app',
    measurementId: 'G-N1Y84J8VLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPlE8UG7V0jqvsAPCuh4nnkz81wIOvVVo',
    appId: '1:812205537802:android:63bba8f21cbe2b3b5a3df3',
    messagingSenderId: '812205537802',
    projectId: 'embti-6e22a',
    storageBucket: 'embti-6e22a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKohR-dGW4HVXDaZvRsHVGyy48BjErMGo',
    appId: '1:812205537802:ios:796e364a4cfbe1f75a3df3',
    messagingSenderId: '812205537802',
    projectId: 'embti-6e22a',
    storageBucket: 'embti-6e22a.firebasestorage.app',
    iosBundleId: 'cn.gritsoft.emombti',
  );
}
